version: 2.0
jobs:
  build:
    docker:
      - image: python:2.7
    working_directory: /gordon-test
    steps:
      - run: cat adsfasdfasdfadsf


  test:
    docker:
      - image: python:2.7
    working_directory: /gordon-test
    steps:
      - run:
          command: cat not_here
          pwd: /

  deploy:
    docker:
      - image: python:2.7
    working_directory: /gordon-test
    steps:
      - run:
          command: echo "deploying! (not really) "
          pwd: /


workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build
      - build-approval:
          type: approval
          requires:
            - build
      - build-approval2:
          type: approval
          required:
            - build-approval
      - test:
          requires:
            - build-approval2

# # testing bad config
# workflows:
#   version: 2
#   build-and-test:
#     jobs:
#       - build
#       - deploy-dev:
#         requires:
#           - build
