version: 2.0
jobs:
  build:
    docker:
      - image: python:2.7
    working_directory: /gordon-test
    steps:
      - run: echo "success!"


  test:
    docker:
      - image: python:2.7
    working_directory: /gordon-test
    steps:
      - run:
          command: cat not_here
          pwd: /

  deploy:
    docker:
      - image: python:2.7
    working_directory: /gordon-test
    steps:
      - run:
          command: echo "deploying! (not really) "
          pwd: /

