version: 2
jobs:
  build:
    docker:
      - image: python:2.7
    resource_class: small
    working_directory: /gordon-test
    steps:
      - checkout

  deploy:
    docker:
      - image: python:2.7
    resource_class: small
    working_directory: /gordon-test
    steps:
      - run:
          command: echo "deploying! (not really) "
          pwd: /

      - run: sleep 2

      - run: echo "Upstream artifacts in ${CIRCLE_UPSTREAM_ARTIFACTS}"

      - run: find ${CIRCLE_UPSTREAM_ARTIFACTS}

      - run: cat ${CIRCLE_UPSTREAM_ARTIFACTS}/build/0/text-data/first

      - run: cat ${CIRCLE_UPSTREAM_ARTIFACTS}/build/0/text-data/second

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build
      - approval-job:
          type: approval
          requires: ["build"]
      - deploy:
          context: awesome-restricted-context
          requires:
            - approval-job
