version: 2.0
jobs:
  build:
    docker:
      - image: python:2.7
    working_directory: /gordon-test
    steps:
      - run: echo adsfasdfasdfadsf


  test:
    docker:
      - image: python:2.7
    working_directory: /gordon-test
    steps:
      - run:
          command: echo hi
          pwd: /

  deploy:
    docker:
      - image: python:2.7
    working_directory: /gordon-test
    steps:
      - run:
          command: echo "deploying! (not really) "
          pwd: /


workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^config-test.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /^config-test.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^config-test.*/
            branches:
              ignore: /.*/
